setwd("~/Dropbox")
t1<-scan("null_standard_normal_stat_noinit.txt")
t1<-t1[which(t1>=0)]
x<-seq(0,max(t1),length=1000)
df1<-mean(scan("null_standard_normal_stat_noinit.txt"))
df2<-mean(t1)
y<-dchisq(x,df1)
z<-dchisq(x,df2)
chisq1<-qchisq(ppoints(length(t1)),df1)
chisq2<-qchisq(ppoints(length(t1)),df2)
png("~/Dropbox/null_standard_normal_stat_noinit.png",width=480*3)
par(mfrow=c(1,3))
hist(scan("null_standard_normal_stat_noinit.txt"),prob=TRUE,main="w/o init",xlab="All LRT test statistics")
lines(x,y,col="blue")
lines(x,z,col="red")
legend("topright",c(expression(chi[1.602]^2),expression(chi[1.669]^2)),col=c("blue","red"),lty=1)
qqplot(chisq1,t1,xlab=expression(chi[1.602]^2),ylab="Non-negative LRT test statistics")
qqline(t1,distribution=function(p) qchisq(p,df=df1))
qqplot(chisq2,t1,xlab=expression(chi[1.669]^2),ylab="Non-negative LRT test statistics")
qqline(t1,distribution=function(p) qchisq(p,df=df2))
dev.off()


t1<-scan("null_standard_normal_stat.txt")
t1<-t1[which(t1>=0)]
x<-seq(0,max(t1),length=1000)
df1<-mean(scan("null_standard_normal_stat.txt"))
df2<-mean(t1)
y<-dchisq(x,df1)
z<-dchisq(x,df2)
chisq1<-qchisq(ppoints(length(t1)),df1)
chisq2<-qchisq(ppoints(length(t1)),df2)
png("~/Dropbox/null_standard_normal_stat.png",width=480*3)
par(mfrow=c(1,3))
hist(scan("null_standard_normal_stat.txt"),prob=TRUE,main="w/ init",xlab="All LRT test statistics")
lines(x,y,col="blue")
lines(x,z,col="red")
legend("topright",c(expression(chi[1.375]^2),expression(chi[1.376]^2)),col=c("blue","red"),lty=1)
qqplot(chisq1,t1,xlab=expression(chi[1.375]^2),ylab="Non-negative LRT test statistics")
qqline(t1,distribution=function(p) qchisq(p,df=df1))
qqplot(chisq2,t1,xlab=expression(chi[1.376]^2),ylab="Non-negative LRT test statistics")
qqline(t1,distribution=function(p) qchisq(p,df=df2))
dev.off()
